---
- name: Include Nginx role
  ansible.builtin.include_role:
    name: nginxinc.nginx

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify:
    - Reload Nginx
